### ISSUE TITLE
Model files are corrupt.

### ISSUE THREAD

**Issue by drewlinsley** [PTRRupprecht/Spikefinder-Elephant#2]
The keras model files do not work (maybe too big for github?). Could you provide links to download? Thanks!

**Comment by PTRRupprecht** [comment]
Hi drewlinsley!

The models are actually very small (each one 493 kB). I just downloaded the repository, and it worked fine in my hands.

So, if I get you right, you get an error when executing the line
> model.load_weights("models/model1.h5")

Such an error could occur if you changed the model definition (in the file 'elephant/2_model.py'). If the model definition (e.g. number of layers etc.) changed, loading the model weight does not work any more, and you have to train your model from scratch.

Are you using the Jupyter File as it is, or have you made some modifications?
