### ISSUE TITLE
Alignment of Ypredict in demo notebook not mentioned

### ISSUE THREAD

**Issue by AdrianRoggenbach** [PTRRupprecht/Spikefinder-Elephant#4]
When testing the Demo.ipynb, I realized that the prediction Ypredict is shifted due to the use of a window with a before_frac of 0.25. This leads to problems with the alignment if one does not take care of this manually.
During plotting, this relative shift was corrected (e.g. ln[10]) by using the indizes variable for the fluorescent signal.
[In 10]:
```
neuron_index = 103
indizes = range(int(windowsize*before_frac),calcium_traceX.shape[0]-int(windowsize*after_frac))
timet = np.arange(0,Ypredict.shape[0])/100
plt.plot(timet,Ypredict[:,neuron_index]*0.5)
plt.plot(timet,tracex[indizes,neuron_index]+9)
```

In plot [Out 10], the fluorescent and inferred spike trace are aligned, but the time axis is shifted by ~300ms. This can lead to problems when aligning the signal to e.g. the recorded stimuli, when users do not realize this and use the deconvolved signal Ypredict[:,neuron] together with the time timet as shown in the example plot.

I would suggest, that the predictions in the demo notebook [ln 7&18] are changed to (similar to 5_make_and_save_predictions.py):
[ln 7&18]:
```
Ypredict = np.zeros( tracex.shape ) * np.nan # with nan padding

for k in range(0,trace.shape[1]):
    if (np.mod(k,20) ==0):
        print('Predicting spikes for neuron %s out of %s' % (k+1, trace.shape[1]))
    x1x = tracex[:,k]
    idx = ~np.isnan(x1x)
    calcium_traceX = norm(x1x[idx])
    # initialize the prediction vector
    XX = np.zeros( (calcium_traceX.shape[0]-windowsize,windowsize,1),dtype = np.float32)
    for jj in range(0,(calcium_traceX.shape[0]-windowsize)):
        XX[jj,:,0] = calcium_traceX[jj:(jj+windowsize)]
    A = model.predict( XX,batch_size = 4096 )

    index = slice( int(windowsize*before_frac), int(windowsize*before_frac+len(A)) )
    Ypredict[ index,k ] = A[:,0]
```

Like this the recorded and deconvolved calcium signal can be plotted using the time vector timet = np.arange(0,Ypredict.shape[0])/100 and alignment issues are avoided.

**Comment by PTRRupprecht** [comment]
I think you're right. When I look at the scripts that I used for spiking prediction analysis more recently, I had fixed this issue as well. It should be fixed now (I also checked that the plots are still fine). - I also implemented your suggestion to use nan- instead of zero-padding. - Thanks for your helpful input.

**Comment by AdrianRoggenbach** [comment]
Thanks for implementing this so quickly!
